# Configuration file for MAPLE

team_number: -1
pose_logging: true
cameras:

  FRONT_CENTER:
    camera_id: 0
    rx: 640
    ry: 480

    # focal length (in pixels)
    fx: 428
    fy: 428

    # center of the camera image (in pixels)
    cx: 320
    cy: 240

    # Camera x, y, z location on the robot, in meters
    translation: [ 0, 0, 1.25 ]

    # Camera roll, pitch, yaw orientation on the robot, in degrees
    rotation: [ 0, 15, 180 ]

    fps: 60.0
    exposure: 100