# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Create a MAPLE .syrup release

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "include/**", "src/**", "lib/**", "test/**", "CMakeLists.txt", "fmap/**" ]

jobs:
  create-arm-release:
    runs-on: ARM64
    timeout-minutes: 120
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Create release
        shell: bash
        run: bash scripts/create-release.sh MAPLE-R25-0-${{ github.run_attempt }}

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: MAPLE-R25-0-${{ github.run_attempt }}_arm64.syrup
          path: |
            release/arm64/MAPLE-R25-0-${{ github.run_attempt }}_arm64.syrup
          retention-days: 120

  create-x86-release:
    runs-on: X64
    timeout-minutes: 120
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Create release
        shell: bash
        run: bash scripts/create-release.sh MAPLE-R25-0-${{ github.run_attempt }}

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: MAPLE-R25-0-${{ github.run_attempt }}_x86.syrup
          path: |
            release/arm64/MAPLE-R25-0-${{ github.run_attempt }}_x86.syrup
          retention-days: 120